lcgcmt_installarea=without_installarea
CMTPATH=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea:/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
CMT_tag=$(tag)
CMTROOT=/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20
CMT_root=/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20
CMTVERSION=v1r20
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/share/bin:/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/share/bin:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/share/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/InstallArea/share/bin:/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/XercesC/2.7.0/slc4_ia32_gcc34/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Python/2.4.2/slc4_ia32_gcc34/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/gccxml/0.6.0_patch3/slc4_ia32_gcc34/bin:/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20/${CMTBIN}:/afs/ihep.ac.cn/users/n/nikolaev/local/bin:/afs/ihep.ac.cn/bes3/offline/sw/packages/Ganga/install/5.3.2/bin/:/usr/bin:/afs/ihep.ac.cn/users/n/nikolaev/bin:/afs/ihep.ac.cn/users/n/nikolaev/scripts:/usr/sue/bin:/bin:/usr/local/bin:/usr/local/bin/X11:/opt/glite/bin:/opt/glite/externals/bin:/opt/lcg/bin:/opt/lcg/sbin:/opt/edg/bin:/opt/edg/sbin:/opt/globus/sbin:/opt/globus/bin:/opt/gpt/sbin:/opt/ufal/bin:/usr/kerberos/bin:/opt/d-cache//srm/bin:/opt/d-cache//dcap/bin:/usr/java/jdk1.5.0_14/bin:/usr/X11R6/bin:${DAWN_HOME}/bin/Linux:${DAWN_HOME}/../bin/Linux:${DAVID_HOME}/bin/Linux:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34/bin
CLASSPATH=/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20/java
debug_option=-g
cc=gcc
cflags= -fmessage-length=0 -fPIC 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags= -fpermissive -fmessage-length=0     -pthread  -D_GNU_SOURCE -pthread -pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-long-long   -march=pentium -mcpu=pentium -pedantic-errors -O2
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -Wl,--no-undefined   -Wl,--export-dynamic 
cpplink=$(cpp) $(cpplinkflags)
for=g77
fflags=-fmessage-length=0 -O2    -fPIC -pipe -fno-second-underscore -Wall -W -Wsurprising -fPIC 
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=flex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=$(ExternalPolicy_root)/scripts/symlink.sh
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory  --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp -R 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(symlink_command)
cmt_uninstall_area_command=$(uninstall_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=i686-slc45-gcc346
JPsi_tag=$(tag)
JPSIROOT=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/JPsi/JPsi-00-00-01
JPsi_root=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/JPsi/JPsi-00-00-01
JPSIVERSION=JPsi-00-00-01
JPsi_cmtpath=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea
JPsi_project=cmthome
JPsi_project_release=workarea
BesPolicy_tag=$(tag)
BESPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/BesPolicy/BesPolicy-01-05-03
BesPolicy_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/BesPolicy/BesPolicy-01-05-03
BESPOLICYVERSION=BesPolicy-01-05-03
BesPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesPolicy_project=boss
BesPolicy_project_release=6.5.1.b
BesCxxPolicy_tag=$(tag)
BESCXXPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/BesCxxPolicy/BesCxxPolicy-00-00-08
BesCxxPolicy_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/BesCxxPolicy/BesCxxPolicy-00-00-08
BESCXXPOLICYVERSION=BesCxxPolicy-00-00-08
BesCxxPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesCxxPolicy_project=boss
BesCxxPolicy_project_release=6.5.1.b
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/GaudiPolicy
GaudiPolicy_root=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/GaudiPolicy
GAUDIPOLICYVERSION=v7r0
GaudiPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v19r4
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Settings
LCG_Settings_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_52a
SITEROOT=/afs/ihep.ac.cn/bes3/offline
LCG_home=${SITEROOT}/sw/lcg
LCG_external=$(LCG_home)/LCGCMT_52a_slc4_ia32_gcc34/external
LCG_releases=$(LCG_home)/app/releases
LCG_system=slc4_ia32_gcc34
LCG_platform=$(LCG_system)
copyInclude=cp -Rup 
dq="
genmap_cmd=$(ROOTSYS)/bin/genmap
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=${GaudiPolicy_root}/cmt/fragments/merge_files.py
libdirname=lib
bindirname=bin
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cppcoverage_s=-fprofile-arcs -ftest-coverage
cdebugflags_s=-g
ccoverage_s=-fprofile-arcs -ftest-coverage
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
fcoverage_s=-fprofile-arcs -ftest-coverage
linkcoverage_s=-L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3 -lgcc
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl -Wl,--no-undefined    -Wl,-s 
libraryshr_linkopts=-fPIC -ldl -Wl,--no-undefined   
application_linkopts=-Wl,--export-dynamic 
genconfDir=genConf
merge_genconfDb_cmd=${GaudiPolicy_root}/cmt/fragments/merge_files.py
genconfig_configurableModuleName=gaudiconf
genconfig_configurableDefaultName=''
genconfig_configurableAlgorithm=configurable
genconfig_configurableAlgTool=configurable
genconfig_configurableAuditor=configurable
genconfig_configurableService=configurable
config_command=cp 
BesCxxPolicy_pp_cppflags= -DHAVE_PRETTY_FUNCTION -DHAVE_LONG_LONG -DHAVE_BOOL -DHAVE_EXPLICIT -DHAVE_MUTABLE -DHAVE_SIGNED -DHAVE_TYPENAME -DHAVE_NEW_STYLE_CASTS -DHAVE_DYNAMIC_CAST -DHAVE_TYPEID -DHAVE_ANSI_TEMPLATE_INSTANTIATION -DHAVE_TEMPLATE_DEFAULT_ARGS -DHAVE_BROKEN_TEMPLATE_RESCOPE -DHAVE_TEMPLATE_NULL_ARGS -DHAVE_TEMPLATE_NULL_SPEC -DHAVE_TEMPLATE_PARTIAL_SPEC -DHAVE_MEMBER_TEMPLATES -DHAVE_ANSI_OPERATOR_ARROW -DHAVE_NAMESPACES -DHAVE_NAMESPACE_STD -DHAVE_NEW_IOSTREAMS -DHAVE_OSTREAM_CHAR_OVERLOAD -DHAVE_ITERATOR_TRAITS -DHAVE_ITERATOR -DHAVE_REVERSE_ITERATOR_STYLE -DHAVE_CXX_STDC_HEADERS '-DPACKAGE_VERSION=$(q2)$(version)$(q2)' 
q2="
BesFortranPolicy_tag=$(tag)
BESFORTRANPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/BesFortranPolicy/BesFortranPolicy-00-01-01
BesFortranPolicy_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/BesFortranPolicy/BesFortranPolicy-00-01-01
BESFORTRANPOLICYVERSION=BesFortranPolicy-00-01-01
BesFortranPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesFortranPolicy_project=boss
BesFortranPolicy_project_release=6.5.1.b
f77_linkopts=-lg2c -lnsl -lcrypt -ldl
f90_home=$(f90_home_linux)
for90=$(for90_linux)
f90pp=$(f90pp_linux)
f90flags=$(f90flags_linux)
f90ppflags=$(f90ppflags_linux)
f90comp=$(f90comp_linux)
f90link=$(f90link_linux)
f90_linkopts=$(f90_linkopts_linux)
BesFortranPolicy_linkopts=$(f77_linkopts)
BesFortranPolicy_export_paths=$(PGI_libset)
BesPolicy_scripts= -s=$(BESPOLICYROOT)/share -s=$(BESPOLICYROOT)/src symlink.sh inverse_symlink.sh get_files 
symlink_command=symlink.sh
symlinknew=$(symlink_command)
copy_command=cp -R
remote_launcher=ssh -f 
application_fragment=application
library_fragment=library
library_no_share_fragment=library_no_share
install_include_filter=*.h
GaudiInterface_tag=$(tag)
GAUDIINTERFACEROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/GaudiInterface/GaudiInterface-01-03-05
GaudiInterface_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/GaudiInterface/GaudiInterface-01-03-05
GAUDIINTERFACEVERSION=GaudiInterface-01-03-05
GaudiInterface_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
GaudiInterface_offset=External
GaudiInterface_project=boss
GaudiInterface_project_release=6.5.1.b
ExternalPolicy_tag=$(tag)
EXTERNALPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/ExternalPolicy/ExternalPolicy-00-00-17
ExternalPolicy_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/ExternalPolicy/ExternalPolicy-00-00-17
EXTERNALPOLICYVERSION=ExternalPolicy-00-00-17
ExternalPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
ExternalPolicy_offset=External
ExternalPolicy_project=boss
ExternalPolicy_project_release=6.5.1.b
ExternalComponents_tag=$(tag)
EXTERNALCOMPONENTSROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/ExternalComponents/ExternalComponents-00-00-32
ExternalComponents_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/ExternalComponents/ExternalComponents-00-00-32
EXTERNALCOMPONENTSVERSION=ExternalComponents-00-00-32
ExternalComponents_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
ExternalComponents_offset=External
ExternalComponents_project=boss
ExternalComponents_project_release=6.5.1.b
GAUDI_DIR=${SITEROOT}/sw/Gaudi/rh72-gcc3.2/GAUDI_v12r0
GAUDI_RELEASE=0.12.1.4
base_URL=http://bes.web.cern.ch/Bes/GROUPS/SOFTWARE/OO/dist/
use_applications= $(cern_apps)
DOTFONTPATH=/lib/fonts/ttf
kits_dir=cmt/kits
zip_command=tar
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/GaudiKernel
GaudiKernel_root=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/GaudiKernel
GAUDIKERNELVERSION=v23r0
GaudiKernel_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v19r4
Reflex_tag=$(tag)
REFLEXROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Reflex
Reflex_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_52a
ROOT_tag=$(tag)
ROOTROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/ROOT
ROOT_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_52a
GCCXML_tag=$(tag)
GCCXMLROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/GCCXML
GCCXML_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_52a
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Configuration
LCG_Configuration_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Configuration
LCG_CONFIGURATIONVERSION=*
LCG_Configuration_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_52a
COOL_config_version=COOL_2_1_1
CORAL_config_version=CORAL_1_8_1
POOL_config_version=POOL_2_5_3
RELAX_config_version=RELAX_1_1_9
ROOT_config_version=5.14.00f
SEAL_config_version=SEAL_1_9_2
AIDA_config_version=3.2.1
Boost_config_version=1.33.1
Boost_file_version=1_33_1
bzlib_config_version=1.0.2
bz2lib_config_version=1.0.2
CASTOR_config_version=2.1.1-9
cernlib_config_version=2005
cgsigsoap_config_version=2.6-1.1.9
CLHEP_config_version=1.9.2.3
CppUnit_config_version=1.10.2_p2
cx_Oracle_config_version=4.1.2
Cygwin_config_version=1.5
dcache_client_config_version=1.7.0.31
EDGRLS_config_version=2.3.3
Expat_config_version=1.95.8
Frontier_Client_config_version=2.7.2
GCCXML_config_version=0.6.0_patch3
Geant4_config_version=4.8.3
gfal_config_version=1.7.7
globusrls_config_version=3.2.1
GSL_config_version=1.8
HepMC_config_version=1.26.02
HepPDT_config_version=2.02.02
HippoDraw_config_version=1.9.0
lfc_config_version=1.5.8
MathLib_config_version=1_0_0
mysql_config_version=5.0.18
mysqlpp_config_version=1.7.40_mysql.5.0.18
oracle_config_version=10.2.0.3
PCRE_config_version=4.4
Python_config_version=2.4.2
pyqt_config_version=3.13_python242
QMtest_config_version=2.3.0_python242
Qt_config_version=3.3.4
rx_config_version=1.5
scons_config_version=0.96.1
sqlite_config_version=3.3.5
uuid_config_version=1.38
vdt_config_version=1.2.3_globusrls215b
XercesC_config_version=2.7.0
zlib_config_version=1.1.4
pcre_config_version=4.4
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
LD_LIBRARY_PATH=/lib:/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/castor/2.1.1-9/slc4_ia32_gcc34/usr/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/XercesC/2.7.0/slc4_ia32_gcc34/lib:${STRING_DIR}/i386_linux26:${ALIST_DIR}/i386_linux26:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepPDT/2.02.02/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepMC/1.26.02/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/1.9.3.1/slc4_ia32_gcc346/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Boost/1.33.1/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/PI/PI_1_3_3/slc3_ia32_gcc323/lib:/usr/lib/gcc/i386-redhat-linux/3.4.6:/opt/c-ares/lib:/opt/glite/lib:/opt/glite/externals/lib:/opt/lcg/lib:/opt/edg/lib:/opt/globus/lib:/opt/d-cache//dcap/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/MySQL/5.0.45/slc4_ia32_gcc34/lib/mysql:/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/genbes/genbes-00-00-08/i386_linux26:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Python/2.4.2/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/LessTif/Motif1.2/lib:${BesGeant4_LIBDIR}/${G4SYSTEM}
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_external)/root/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread 
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root
ROOT_name=root
list_cmd=$(LCG_Settings_root)/scripts/list_files.sh --type $(shlibsuffix) $(cernlib_home)/lib 
PYTHONPATH=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/lib:/opt/lcg/lib:/opt/lcg/lib/python:/opt/edg/lib:/opt/edg/lib/python:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/PI/PI_1_3_3/slc3_ia32_gcc323/python
rootcint=rootcint
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
Boost_tag=$(tag)
BOOSTROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Boost
Boost_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_52a
Boost_native_version=$(Boost_config_version)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_linkopts=-L$(Boost_home)/lib 
Boost_linkopts_python= -lboost_python-gcc 
Boost_linkopts_filesystem= -lboost_filesystem-gcc 
Boost_linkopts_regex= -lboost_regex-gcc 
Boost_linkopts_thread= -lboost_thread-gcc-mt 
Boost_linkopts_program_options= -lboost_program_options-gcc-mt 
Boost_export_paths=$(Boost_home)
Python_tag=$(tag)
PYTHONROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Python
Python_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_52a
Python_native_version=$(Python_config_version)
Python_version=2.4
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_version) -lutil -lpthread 
Python_export_paths=$(Python_home)
includes= $(ppcmd)"/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/include/JPsi" $(ppcmd)"/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/include" $(use_includes)
GaudiKernel_linkopts= -lGaudiKernel 
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
GaudiKernel_reflex_selection_file= $(GAUDIKERNELROOT)/dict/dictionary.xml 
GaudiKernel_rootmap=$(CMTINSTALLAREA)/$(tag)/lib/rootmap
GaudiKernel_reflex_options=  $(gccxmlopts) --select=$(GAUDIKERNELROOT)/dict/dictionary.xml  --gccxmlpath=$(GCCXML_home)/bin
GaudiKernelDict_dependencies=$(GaudiKernel_linker_library) GaudiKernelGen
GaudiKernelDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(GaudiKernel_linkopts) $(GaudiKernelDict_use_linkopts) 
GaudiKernelDict_use_linkopts=$(use_linkopts)
genconfig_cmd=$(GaudiKernel_cmtpath)/$(GAUDI_installarea_prefix)/$(tag)/bin/genconf.exe
GAUDIEXE=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/i386_linux26/bin/Gaudi.exe
Gaudi=${GAUDIEXE}
DstEvent_tag=$(tag)
DSTEVENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/DstEvent/DstEvent-00-02-42
DstEvent_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/DstEvent/DstEvent-00-02-42
DSTEVENTVERSION=DstEvent-00-02-42
DstEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
DstEvent_offset=Event
DstEvent_project=boss
DstEvent_project_release=6.5.1.b
BesCLHEP_tag=$(tag)
BESCLHEPROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesCLHEP/BesCLHEP-00-00-04
BesCLHEP_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesCLHEP/BesCLHEP-00-00-04
BESCLHEPVERSION=BesCLHEP-00-00-04
BesCLHEP_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesCLHEP_offset=External
BesCLHEP_project=boss
BesCLHEP_project_release=6.5.1.b
CLHEP_tag=$(tag)
CLHEPROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/CLHEP
CLHEP_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/CLHEP
CLHEPVERSION=v1
CLHEP_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
CLHEP_offset=LCG_Interfaces
CLHEP_project=LCGCMT
CLHEP_project_release=LCGCMT_52a
CLHEP_native_version=1.9.3.1
CLHEP_home=/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/1.9.3.1/slc4_ia32_gcc346
CLHEP_linkopts=-L$(CLHEP_home)/lib         -lCLHEP-Cast-$(CLHEP_native_version)        -lCLHEP-Evaluator-$(CLHEP_native_version)        -lCLHEP-Exceptions-$(CLHEP_native_version)        -lCLHEP-GenericFunctions-$(CLHEP_native_version)        -lCLHEP-Geometry-$(CLHEP_native_version)        -lCLHEP-Random-$(CLHEP_native_version)        -lCLHEP-RandomObjects-$(CLHEP_native_version)        -lCLHEP-RefCount-$(CLHEP_native_version)         -lCLHEP-Vector-$(CLHEP_native_version)        -lCLHEP-Matrix-$(CLHEP_native_version)   -L${ALIST_DIR}/i386_linux26 -lAlist -L${STRING_DIR}/i386_linux26 -lString 
CLHEP_name=clhep
CLHEP_export_paths=$(CLHEP_home)/include $(CLHEP_home)/lib
HepMC_tag=$(tag)
HEPMCROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/HepMC
HepMC_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/HepMC
HEPMCVERSION=v1
HepMC_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
HepMC_offset=LCG_Interfaces
HepMC_project=LCGCMT
HepMC_project_release=LCGCMT_52a
HepMC_native_version=$(HepMC_config_version)
HepMC_home=$(LCG_external)/HepMC/$(HepMC_native_version)/$(LCG_system)
HepMC_linkopts=-L$(HepMC_home)/lib -lHepMC  
HepMC_export_paths=$(HepMC_home)/include $(HepMC_home)/lib
HepPDT_tag=$(tag)
HEPPDTROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/HepPDT
HepPDT_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/HepPDT
HEPPDTVERSION=v1
HepPDT_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
HepPDT_offset=LCG_Interfaces
HepPDT_project=LCGCMT
HepPDT_project_release=LCGCMT_52a
HepPDT_native_version=$(HepPDT_config_version)
HepPDT_home=$(LCG_external)/HepPDT/$(HepPDT_native_version)/$(LCG_system)
HepPDT_linkopts=-L$(HepPDT_home)/lib -lHepPDT -lHepPID 
HepPDT_export_paths=$(HepPDT_home)/include $(HepPDT_home)/lib
BesExternalArea_tag=$(tag)
BESEXTERNALAREAROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesExternalArea/BesExternalArea-00-00-18
BesExternalArea_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesExternalArea/BesExternalArea-00-00-18
BESEXTERNALAREAVERSION=BesExternalArea-00-00-18
BesExternalArea_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesExternalArea_offset=External
BesExternalArea_project=boss
BesExternalArea_project_release=6.5.1.b
LCG_ROOT=${SITEROOT}/sw/lcg
LCG_EXTERNAL=${LCG_ROOT}/external
LCG_app_system=rh73_gcc32
LCG_ext_system=rh73_gcc32
BES_EXTERNAL=${SITEROOT}/sw/external
BESTESTDATA=${SITEROOT}/bes/offline/data/testfile
BESCALDATA=${SITEROOT}/bes/offline/data/${BES_RELEASE}
COMMON_PACKAGES=${SITEROOT}/sw/packages
ALIST_DIR=/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/Alist/Alist-00-00-02
STRING_DIR=/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/String/String-00-00-02
CLHEP_pp_cppflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
CLHEP_pp_fflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
EventModel_tag=$(tag)
EVENTMODELROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EventModel/EventModel-01-05-29
EventModel_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EventModel/EventModel-01-05-29
EVENTMODELVERSION=EventModel-01-05-29
EventModel_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
EventModel_offset=Event
EventModel_project=boss
EventModel_project_release=6.5.1.b
EventModel_linkopts= -L$(bin) -lEventModel  
DstEvent_linkopts= -L$(bin) -lDstEvent  
EvtRecEvent_tag=$(tag)
EVTRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EvtRecEvent/EvtRecEvent-00-01-04
EvtRecEvent_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EvtRecEvent/EvtRecEvent-00-01-04
EVTRECEVENTVERSION=EvtRecEvent-00-01-04
EvtRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
EvtRecEvent_offset=Event
EvtRecEvent_project=boss
EvtRecEvent_project_release=6.5.1.b
EvTimeEvent_tag=$(tag)
EVTIMEEVENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EvTimeEvent/EvTimeEvent-00-00-08
EvTimeEvent_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EvTimeEvent/EvTimeEvent-00-00-08
EVTIMEEVENTVERSION=EvTimeEvent-00-00-08
EvTimeEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
EvTimeEvent_offset=Event
EvTimeEvent_project=boss
EvTimeEvent_project_release=6.5.1.b
MdcGeomSvc_tag=$(tag)
MDCGEOMSVCROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Mdc/MdcGeomSvc/MdcGeomSvc-00-01-28
MdcGeomSvc_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Mdc/MdcGeomSvc/MdcGeomSvc-00-01-28
MDCGEOMSVCVERSION=MdcGeomSvc-00-01-28
MdcGeomSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
MdcGeomSvc_offset=Mdc
MdcGeomSvc_project=boss
MdcGeomSvc_project_release=6.5.1.b
calibUtil_tag=$(tag)
CALIBUTILROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/calibUtil/calibUtil-00-00-22
calibUtil_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/calibUtil/calibUtil-00-00-22
CALIBUTILVERSION=calibUtil-00-00-22
calibUtil_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
calibUtil_offset=Calibration
calibUtil_project=boss
calibUtil_project_release=6.5.1.b
facilities_tag=$(tag)
FACILITIESROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/facilities/facilities-00-00-01
facilities_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/facilities/facilities-00-00-01
FACILITIESVERSION=facilities-00-00-01
facilities_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
facilities_offset=Calibration
facilities_project=boss
facilities_project_release=6.5.1.b
facilities_linkopts= -lfacilities 
xmlBase_tag=$(tag)
XMLBASEROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/xmlBase/xmlBase-00-00-02
xmlBase_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/xmlBase/xmlBase-00-00-02
XMLBASEVERSION=xmlBase-00-00-02
xmlBase_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
xmlBase_offset=Calibration
xmlBase_project=boss
xmlBase_project_release=6.5.1.b
XercesC_tag=$(tag)
XERCESCROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/XercesC
XercesC_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/XercesC
XERCESCVERSION=v1
XercesC_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
XercesC_offset=LCG_Interfaces
XercesC_project=LCGCMT
XercesC_project_release=LCGCMT_52a
XercesC_native_version=$(XercesC_config_version)
XercesC_home=$(LCG_external)/XercesC/$(XercesC_native_version)/$(LCG_system)
XercesC_linkopts=-L$(XercesC_home)/lib -lxerces-c -lxerces-depdom -lpthread
XercesC_warnings=-w -Wno-unused
XercesC_export_paths= $(XercesC_home)/include $(XercesC_home)/lib
xmlBase_linkopts=-L$(XMLBASEROOT)/$(xmlBase_tag) -lxmlBase  
rdbModel_tag=$(tag)
RDBMODELROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/rdbModel/rdbModel-00-00-12
rdbModel_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/rdbModel/rdbModel-00-00-12
RDBMODELVERSION=rdbModel-00-00-12
rdbModel_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
rdbModel_offset=Calibration
rdbModel_project=boss
rdbModel_project_release=6.5.1.b
MYSQL_tag=$(tag)
MYSQLROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/MYSQL/MYSQL-00-00-07
MYSQL_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/MYSQL/MYSQL-00-00-07
MYSQLVERSION=MYSQL-00-00-07
MYSQL_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
MYSQL_offset=External
MYSQL_project=boss
MYSQL_project_release=6.5.1.b
MYSQL_native_version=5.0.45
MYSQLBASE=${COMMON_PACKAGES}/MySQL/$(MYSQL_native_version)/slc4_ia32_gcc34
MYSQL_linkopts=-L$(MYSQLBASE)/lib/mysql -lmysqlclient -lz 
rdbModel_linkopts=-L$(RDBMODELROOT)/$(rdbModel_tag) -lrdbModel  
MYSQL_HOST=localhost
MYSQL_METATABLE=metadata_v0r1
calibUtil_linkopts=-L$(CALIBUTILROOT)/$(calibUtil_tag) -lcalibUtil  
CalibData_tag=$(tag)
CALIBDATAROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/CalibData/CalibData-00-00-34
CalibData_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Calibration/CalibData/CalibData-00-00-34
CALIBDATAVERSION=CalibData-00-00-34
CalibData_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
CalibData_offset=Calibration
CalibData_project=boss
CalibData_project_release=6.5.1.b
CalibData_linkopts= -L$(bin) -lCalibData  
MdcGeomSvcLib_files=*.cxx
MdcGeomSvc_dependencies= MdcGeomSvcLib
MdcGeomSvcstamps= $(bin)/MdcGeomSvcLib.stamp $(bin)/MdcGeomSvcsetup.make 
MdcGeomSvc_linkopts= -L$(bin) -lMdcGeomSvcLib
MdcGeomSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
RelTable_tag=$(tag)
RELTABLEROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/RelTable/RelTable-00-00-02
RelTable_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/RelTable/RelTable-00-00-02
RELTABLEVERSION=RelTable-00-00-02
RelTable_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
RelTable_offset=Event
RelTable_project=boss
RelTable_project_release=6.5.1.b
Identifier_tag=$(tag)
IDENTIFIERROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/Identifier/Identifier-00-02-10
Identifier_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/Identifier/Identifier-00-02-10
IDENTIFIERVERSION=Identifier-00-02-10
Identifier_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
Identifier_offset=DetectorDescription
Identifier_project=boss
Identifier_project_release=6.5.1.b
Identifier_linkopts= -L$(bin) -lIdentifier  
EvTimeEvent_linkopts= -L$(bin) -lEvTimeEvent  
MdcRecEvent_tag=$(tag)
MDCRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Mdc/MdcRecEvent/MdcRecEvent-00-05-11
MdcRecEvent_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Mdc/MdcRecEvent/MdcRecEvent-00-05-11
MDCRECEVENTVERSION=MdcRecEvent-00-05-11
MdcRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
MdcRecEvent_offset=Mdc
MdcRecEvent_project=boss
MdcRecEvent_project_release=6.5.1.b
MdcRecEvent_linkopts= -L$(bin) -lMdcRecEvent  
TofRecEvent_tag=$(tag)
TOFRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Tof/TofRecEvent/TofRecEvent-00-02-14
TofRecEvent_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Tof/TofRecEvent/TofRecEvent-00-02-14
TOFRECEVENTVERSION=TofRecEvent-00-02-14
TofRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
TofRecEvent_offset=Tof
TofRecEvent_project=boss
TofRecEvent_project_release=6.5.1.b
TofRecEvent_linkopts= -L$(bin) -lTofRecEvent  
EmcRecEventModel_tag=$(tag)
EMCRECEVENTMODELROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Emc/EmcRecEventModel/EmcRecEventModel-01-01-17
EmcRecEventModel_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Emc/EmcRecEventModel/EmcRecEventModel-01-01-17
EMCRECEVENTMODELVERSION=EmcRecEventModel-01-01-17
EmcRecEventModel_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
EmcRecEventModel_offset=Emc
EmcRecEventModel_project=boss
EmcRecEventModel_project_release=6.5.1.b
EmcRecGeoSvc_tag=$(tag)
EMCRECGEOSVCROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Emc/EmcRecGeoSvc/EmcRecGeoSvc-01-01-06
EmcRecGeoSvc_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Emc/EmcRecGeoSvc/EmcRecGeoSvc-01-01-06
EMCRECGEOSVCVERSION=EmcRecGeoSvc-01-01-06
EmcRecGeoSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
EmcRecGeoSvc_offset=Emc
EmcRecGeoSvc_project=boss
EmcRecGeoSvc_project_release=6.5.1.b
ROOTGeo_tag=$(tag)
ROOTGEOROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/ROOTGeo/ROOTGeo-00-00-14
ROOTGeo_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/ROOTGeo/ROOTGeo-00-00-14
ROOTGEOVERSION=ROOTGeo-00-00-14
ROOTGeo_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
ROOTGeo_offset=DetectorDescription
ROOTGeo_project=boss
ROOTGeo_project_release=6.5.1.b
BesROOT_tag=$(tag)
BESROOTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesROOT/BesROOT-00-00-06
BesROOT_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesROOT/BesROOT-00-00-06
BESROOTVERSION=BesROOT-00-00-06
BesROOT_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesROOT_offset=External
BesROOT_project=boss
BesROOT_project_release=6.5.1.b
CASTOR_tag=$(tag)
CASTORROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/CASTOR
CASTOR_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/CASTOR
CASTORVERSION=v1
CASTOR_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
CASTOR_offset=LCG_Interfaces
CASTOR_project=LCGCMT
CASTOR_project_release=LCGCMT_52a
CASTOR_native_version=$(CASTOR_config_version)
CASTOR_name=castor
CASTOR_home=$(LCG_external)/$(CASTOR_name)/$(CASTOR_native_version)/$(LCG_system)/usr
CASTOR_libdir=lib
CASTOR_linkopts=-L$(CASTOR_home)/$(CASTOR_libdir) -lshift 
CASTOR_export_paths=$(CASTOR_home)/include $(CASTOR_home)/$(CASTOR_libdir)
rootBasicLibs=-L$(ROOT_home)/lib -lCore -lCint -lTree -lRFIO
rootMathLibs=-L$(ROOT_home)/lib   -lMLP -lMinuit -lMatrix -lPhysics -lHistPainter -lHist -lRint
rootGraphicsLibs=-L$(ROOT_home)/lib -lGraf -lGraf3d -lGpad -lHtml -lPostscript -lGui -lGX11TTF -lGX11 -lASImageGui -lASImage -lGeom -lGeomPainter -lX3d -lRGL -lVMC 
rootTableLibs=-L$(ROOT_home)/lib -lTable
rootSTLDictLibs= -L${ROOT_home}/lib -ldequeDict -llistDict -lmapDict -lmap2Dict -lmultimapDict -lmultimap2Dict -lmultisetDict -lsetDict -lvectorDict 
BesROOT_linkopts= $(rootMathLibs) $(rootBasicLibs) $(rootGraphicsLibs) $(rootTableLibs) $(rootSTLDictLibs) 
GdmlToRoot_tag=$(tag)
GDMLTOROOTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/GdmlToRoot/GdmlToRoot-00-00-10
GdmlToRoot_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/GdmlToRoot/GdmlToRoot-00-00-10
GDMLTOROOTVERSION=GdmlToRoot-00-00-10
GdmlToRoot_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
GdmlToRoot_offset=External
GdmlToRoot_project=boss
GdmlToRoot_project_release=6.5.1.b
GdmlToRoot_path=${COMMON_PACKAGES}/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML
GdmlToRoot_LIBDIR=${GdmlToRoot_path}/lib
GdmlToRoot_linkopts=-L$(GdmlToRoot_LIBDIR)  -lProcesses -lSaxana -lWriter -lEvaluator -lProcessor -lSubscribers
GdmlManagement_tag=$(tag)
GDMLMANAGEMENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/GdmlManagement/GdmlManagement-00-00-25
GdmlManagement_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/GdmlManagement/GdmlManagement-00-00-25
GDMLMANAGEMENTVERSION=GdmlManagement-00-00-25
GdmlManagement_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
GdmlManagement_offset=DetectorDescription
GdmlManagement_project=boss
GdmlManagement_project_release=6.5.1.b
ROOTGeoLib_files=*.cxx
ROOTGeo_dependencies= ROOTGeoLib
ROOTGeostamps= $(bin)/ROOTGeoLib.stamp $(bin)/ROOTGeosetup.make 
ROOTGeo_linkopts= -L$(bin) -lROOTGeoLib
ROOTGeo_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
EmcRecGeoSvcLib_files=*.cxx
EmcRecGeoSvc_dependencies= EmcRecGeoSvcLib
EmcRecGeoSvcstamps= $(bin)/EmcRecGeoSvcLib.stamp $(bin)/EmcRecGeoSvcsetup.make 
EmcRecGeoSvc_linkopts= -L$(bin) -lEmcRecGeoSvcLib
EmcRecGeoSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
EmcRecEventModel_linkopts= -L$(bin) -lEmcRecEventModel  
MucRecEvent_tag=$(tag)
MUCRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Muc/MucRecEvent/MucRecEvent-00-02-46
MucRecEvent_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Muc/MucRecEvent/MucRecEvent-00-02-46
MUCRECEVENTVERSION=MucRecEvent-00-02-46
MucRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
MucRecEvent_offset=Muc
MucRecEvent_project=boss
MucRecEvent_project_release=6.5.1.b
ExtEvent_tag=$(tag)
EXTEVENTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/ExtEvent/ExtEvent-00-00-12
ExtEvent_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/ExtEvent/ExtEvent-00-00-12
EXTEVENTVERSION=ExtEvent-00-00-12
ExtEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
ExtEvent_offset=Event
ExtEvent_project=boss
ExtEvent_project_release=6.5.1.b
ExtEvent_linkopts= -L$(bin) -lExtEvent  
MucGeomSvc_tag=$(tag)
MUCGEOMSVCROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Muc/MucGeomSvc/MucGeomSvc-00-02-24
MucGeomSvc_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Muc/MucGeomSvc/MucGeomSvc-00-02-24
MUCGEOMSVCVERSION=MucGeomSvc-00-02-24
MucGeomSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
MucGeomSvc_offset=Muc
MucGeomSvc_project=boss
MucGeomSvc_project_release=6.5.1.b
G4Geo_tag=$(tag)
G4GEOROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/G4Geo/G4Geo-00-00-10
G4Geo_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/G4Geo/G4Geo-00-00-10
G4GEOVERSION=G4Geo-00-00-10
G4Geo_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
G4Geo_offset=DetectorDescription
G4Geo_project=boss
G4Geo_project_release=6.5.1.b
BesGeant4_tag=$(tag)
BESGEANT4ROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesGeant4/BesGeant4-00-00-01
BesGeant4_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/BesGeant4/BesGeant4-00-00-01
BESGEANT4VERSION=BesGeant4-00-00-01
BesGeant4_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesGeant4_offset=External
BesGeant4_project=boss
BesGeant4_project_release=6.5.1.b
LessTif_tag=$(tag)
LESSTIFROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/LessTif/LessTif-00-00-05
LessTif_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/LessTif/LessTif-00-00-05
LESSTIFVERSION=LessTif-00-00-05
LessTif_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
LessTif_offset=External
LessTif_project=boss
LessTif_project_release=6.5.1.b
Xt_tag=$(tag)
XTROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/Xt/Xt-00-00-02
Xt_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/Xt/Xt-00-00-02
XTVERSION=Xt-00-00-02
Xt_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
Xt_offset=External
Xt_project=boss
Xt_project_release=6.5.1.b
Xt_native_version=X11R6
Xt_home=/usr/$(Xt_native_version)
Xt_linkopts=-L$(Xt_home)/lib -lXt -lSM -lICE -lXpm -lX11 -lXi -lXext
LessTif_native_version_rh61=2.0
LessTif_native_version_rh73=2.1
LessTif_DIR_rh61=$(Xt_home)
LessTif_DIR_rh73=$(Xt_home)
LessTif_native_version=1.2
LessTif_DIR=$(COMMON_PACKAGES)
LessTif_home=$(LessTif_DIR)/LessTif/Motif$(LessTif_native_version)
LessTif_linkopts= -L$(LessTif_home)/lib -lXm 
BesGeant4_PACKAGE=/afs/ihep.ac.cn/bes3/offline/sw/packages/geant4
BesGeant4_VERSION=4.9.0
BesGeant4_ARCH=slc4_ia32_gcc346
BesGeant4_PATH=${BesGeant4_PACKAGE}/$(BesGeant4_VERSION)/$(BesGeant4_ARCH)/geant4.9.0.p01
G4INCLUDE=/afs/ihep.ac.cn/bes3/offline/sw/packages/geant4/4.9.0/slc4_ia32_gcc346/geant4.9.0.p01/include
BesGeant4_LIBDIR=/afs/ihep.ac.cn/bes3/offline/sw/packages/geant4/4.9.0/slc4_ia32_gcc346/geant4.9.0.p01/lib
G4SYSTEM=Linux-g++
BesGeant4_DATA=/afs/ihep.ac.cn/bes3/offline/sw/packages/geant4/4.9.0/slc4_ia32_gcc346/geant4.9.0.p01/data
G4LEDATA=${BesGeant4_DATA}/G4EMLOW4.3
NeutronHPCrossSections=${BesGeant4_DATA}/G4NDL3.11
G4LEVELGAMMADATA=${BesGeant4_DATA}/PhotonEvaporation2.0
G4RADIOACTIVEDATA=${BesGeant4_DATA}/RadiativeDecay3.2
BesGeant4_linkopts= -L${BesGeant4_LIBDIR}/$(G4SYSTEM)       -lG4baryons       -lG4biasing       -lG4bosons       -lG4brep       -lG4csg       -lG4cuts       -lG4decay       -lG4detector       -lG4detutils       -lG4digits       -lG4emhighenergy       -lG4emlowenergy       -lG4empolar       -lG4emstandard       -lG4emutils       -lG4error_propagation       -lG4event       -lG4FR       -lG4geombias       -lG4geomBoolean       -lG4geomdivision       -lG4geometrymng       -lG4gflash       -lG4globman       -lG4graphics_reps       -lG4had_im_r_matrix       -lG4had_lll_fis       -lG4had_mod_man       -lG4had_mod_util       -lG4had_muon_nuclear       -lG4had_neu_hp       -lG4had_preequ_exciton       -lG4hadronic_ablation       -lG4hadronic_abrasion       -lG4hadronic_bert_cascade       -lG4hadronic_binary       -lG4hadronic_body_ci       -lG4hadronic_coherent_elastic       -lG4hadronic_deex_evaporation       -lG4hadronic_deex_fermi_breakup       -lG4hadronic_deex_fission       -lG4hadronic_deex_gem_evaporation       -lG4hadronic_deex_handler       -lG4hadronic_deex_management       -lG4hadronic_deex_multifragmentation       -lG4hadronic_deex_photon_evaporation       -lG4hadronic_deex_util       -lG4hadronic_em_dissociation       -lG4hadronic_HE       -lG4hadronic_hetcpp_evaporation       -lG4hadronic_hetcpp_utils       -lG4hadronic_interface_ci       -lG4hadronic_iso       -lG4hadronic_leading_particle       -lG4hadronic_LE       -lG4hadronic_mgt       -lG4hadronic_proc       -lG4hadronic_qgstring       -lG4hadronic_radioactivedecay       -lG4hadronic_stop       -lG4hadronic_util       -lG4hadronic_xsect       -lG4had_string_diff       -lG4had_string_frag       -lG4had_string_man       -lG4had_theo_max       -lG4hepnumerics       -lG4hits       -lG4intercoms       -lG4ions       -lG4leptons       -lG4magneticfield       -lG4materials       -lG4mesons       -lG4modeling       -lG4muons       -lG4navigation       -lG4OpenGL       -lG4optical       -lG4parameterisation       -lG4partman       -lG4partutils       -lG4persistency       -lG4phys_builders       -lG4phys_lists       -lG4procman       -lG4RayTracer       -lG4readout       -lG4run       -lG4scoring       -lG4shortlived       -lG4specsolids       -lG4tracking       -lG4track       -lG4transportation       -lG4Tree       -lG4UIbasic       -lG4UIcommon       -lG4UIGAG       -lG4visHepRep       -lG4vis_management       -lG4visXXX       -lG4volumes       -lG4VRML       -lG4xrays       -lXm
BesGeant4_cppflags= -W -Wall -ansi -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -pipe -O2 -fPIC  -DG4OPTIMIZE -DG4VERBOSE -DG4_STORE_TRAJECTORY  -DG4UI_USE_TCSH -DG4VIS_USE_DAWNFILE -DG4VIS_USE_HEPREPFILE -DG4VIS_USE_RAYTRACER -DG4VIS_USE_VRMLFILE -DG4VIS_USE_ASCIITREE -DG4VIS_USE_GAGTREE -DG4VIS_USE_DAWN -DG4VIS_USE_OPENGLX -DG4VIS_USE_OPENGL -DG4VIS_USE_RAYTRACERX -DG4VIS_USE 
DAWN_HOME=${SITEROOT}/sw/contrib/DAWN/3.85
DAVID_HOME=${SITEROOT}/sw/contrib/DAVID/1.34
DAWN_BSD_UNIX_DOMAIN=1
DAWN_GUI_ALWAYS=1
G4VIS_USE_DAWN=1
G4VIS_USE_DAWNFILE=1
G4DAWNFILE_VIEWER=dawn
G4VIS_USE_OPENGLX=1
G4VIS_USE=1
GdmlToG4_tag=$(tag)
GDMLTOG4ROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/GdmlToG4/GdmlToG4-00-00-07
GdmlToG4_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/GdmlToG4/GdmlToG4-00-00-07
GDMLTOG4VERSION=GdmlToG4-00-00-07
GdmlToG4_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
GdmlToG4_offset=External
GdmlToG4_project=boss
GdmlToG4_project_release=6.5.1.b
GdmlToG4_path=${COMMON_PACKAGES}/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML
GdmlToG4_LIBDIR=${GdmlToG4_path}/lib
GdmlToG4_linkopts=-L$(GdmlToG4_LIBDIR) -lProcesses -lSaxana -lWriter -lG4Evaluator -lG4Processor -lG4Subscribers -lG4Writer
G4GeoLib_files=*.cxx
G4Geo_dependencies= G4GeoLib
G4Geostamps= $(bin)/G4GeoLib.stamp $(bin)/G4Geosetup.make 
G4Geo_linkopts= -L$(bin) -lG4GeoLib
G4Geo_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MucGeomSvcLib_files=*.cxx
MucGeomSvc_dependencies= MucGeomSvcLib
MucGeomSvcstamps= $(bin)/MucGeomSvcLib.stamp $(bin)/MucGeomSvcsetup.make 
MucGeomSvc_linkopts= -L$(bin) -lMucGeomSvcLib
MucGeomSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MucRecEvent_linkopts= -L$(bin) -lMucRecEvent  
EvtRecEvent_linkopts= -L$(bin) -lEvtRecEvent  
VertexFit_tag=$(tag)
VERTEXFITROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Analysis/VertexFit/VertexFit-00-02-29
VertexFit_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Analysis/VertexFit/VertexFit-00-02-29
VERTEXFITVERSION=VertexFit-00-02-29
VertexFit_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
VertexFit_offset=Analysis
VertexFit_project=boss
VertexFit_project_release=6.5.1.b
MagneticField_tag=$(tag)
MAGNETICFIELDROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/MagneticField/MagneticField-00-01-27
MagneticField_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/MagneticField/MagneticField-00-01-27
MAGNETICFIELDVERSION=MagneticField-00-01-27
MagneticField_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
MagneticField_project=boss
MagneticField_project_release=6.5.1.b
ReadDBBase_tag=$(tag)
READDBBASEROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Database/ReadDBBase/ReadDBBase-00-00-01
ReadDBBase_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Database/ReadDBBase/ReadDBBase-00-00-01
READDBBASEVERSION=ReadDBBase-00-00-01
ReadDBBase_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
ReadDBBase_offset=Database
ReadDBBase_project=boss
ReadDBBase_project_release=6.5.1.b
ReadDBBaseLib_files=*.cxx
ReadDBBase_dependencies= ReadDBBaseLib
ReadDBBasestamps= $(bin)/ReadDBBaseLib.stamp $(bin)/ReadDBBasesetup.make 
ReadDBBase_linkopts= -L$(bin) -lReadDBBaseLib
ReadDBBase_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
BesTimerSvc_tag=$(tag)
BESTIMERSVCROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Utilities/BesTimerSvc/BesTimerSvc-00-00-11
BesTimerSvc_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Utilities/BesTimerSvc/BesTimerSvc-00-00-11
BESTIMERSVCVERSION=BesTimerSvc-00-00-11
BesTimerSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
BesTimerSvc_offset=Utilities
BesTimerSvc_project=boss
BesTimerSvc_project_release=6.5.1.b
BesTimerSvcLib_files=*.cxx
BesTimerSvc_dependencies= BesTimerSvcLib
BesTimerSvcstamps= $(bin)/BesTimerSvcLib.stamp $(bin)/BesTimerSvcsetup.make 
BesTimerSvc_linkopts= -L$(bin) -lBesTimerSvcLib
BesTimerSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MagneticField_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MagneticFieldstamps= $(bin)/MagneticFieldsetup.make 
VertexFit_linkopts=-L$(bin) -lVertexFit   -lVertexFit 
VertexFit_cppflags= -w 
VertexFit_stamps=${VERTEXFITROOT}/${BINDIR}/VertexFit.stamp 
ParticleID_tag=$(tag)
PARTICLEIDROOT=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Analysis/ParticleID/ParticleID-00-04-29
ParticleID_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Analysis/ParticleID/ParticleID-00-04-29
PARTICLEIDVERSION=ParticleID-00-04-29
ParticleID_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
ParticleID_offset=Analysis
ParticleID_project=boss
ParticleID_project_release=6.5.1.b
CERNLIB_tag=$(tag)
CERNLIBROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/cernlib
CERNLIB_root=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/External/CERNLIB/CERNLIB-01-02-01
CERNLIBVERSION=v1
CERNLIB_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b
CERNLIB_offset=External
CERNLIB_project=boss
CERNLIB_project_release=6.5.1.b
cernlib_tag=$(tag)
cernlib_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/LCG_Interfaces/cernlib
cernlib_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a
cernlib_offset=LCG_Interfaces
cernlib_project=LCGCMT
cernlib_project_release=LCGCMT_52a
cernlib_native_version=$(cernlib_config_version)
cernlib_base=$(LCG_external)/cernlib/$(cernlib_native_version)
cernlib_home=$(cernlib_base)/$(LCG_system)
graflib=-L$(cernlib_home)/lib  -lgraflib -lgrafX11 -lpacklib -L/usr/X11R6/lib -lX11 
cernlib_linkopts= -L$(cernlib_home)/lib -lphotos202 -lpythia6205  -lpdflib804 -lmathlib -lpawlib -llapack3 -lblas -lgraflib -lgrafX11 -lpacklib -lmathlib -lphtools -lkernlib -L/usr/X11R6/lib -lX11  -lg2c $(BesShift_linkopts) -lshift -lnsl -lcrypt -ldl -lg2c
cernlib_fflags= -DCERNLIB_TYPE -DCERNLIB_LINUX
cernlib_export_paths=$(cernlib_home)/include $(cernlib_home)/bin $(cernlib_home)/lib
CERN=/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34
CERN_LEVEL=.
ParticleID_linkopts= -L$(bin) -lParticleID  
ParticleID_cppflags= -DYDEBUG -DMEMWATCH -DMEMWATCH_STDIO  -Df2cFortran -w
ParticleID_fflags=  -fno-automatic -ffixed-line-length-132 -fbackslash  -w
JPsi_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
JPsistamps= $(bin)/JPsisetup.make 
JPsi_runtime= -s=../share *.txt  
use_runtime= $(JPsi_runtime) 
install_runtime_dependencies=JPsi_check_install_runtime
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
BesCxxPolicyDir=${BESCXXPOLICYROOT}/${BINDIR}
BesPolicyDir=${BESPOLICYROOT}/${BINDIR}
ExternalPolicyDir=${EXTERNALPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
GaudiInterfaceDir=${GAUDIINTERFACEROOT}/${BINDIR}
BesExternalAreaDir=${BESEXTERNALAREAROOT}/${BINDIR}
BesCLHEPDir=${BESCLHEPROOT}/${BINDIR}
EventModelDir=${EVENTMODELROOT}/${BINDIR}
DstEventDir=${DSTEVENTROOT}/${BINDIR}
facilitiesDir=${FACILITIESROOT}/${BINDIR}
xmlBaseDir=${XMLBASEROOT}/${BINDIR}
MYSQLDir=${MYSQLROOT}/${BINDIR}
rdbModelDir=${RDBMODELROOT}/${BINDIR}
calibUtilDir=${CALIBUTILROOT}/${BINDIR}
CalibDataDir=${CALIBDATAROOT}/${BINDIR}
MdcGeomSvcDir=${MDCGEOMSVCROOT}/${BINDIR}
RelTableDir=${RELTABLEROOT}/${BINDIR}
IdentifierDir=${IDENTIFIERROOT}/${BINDIR}
EvTimeEventDir=${EVTIMEEVENTROOT}/${BINDIR}
MdcRecEventDir=${MDCRECEVENTROOT}/${BINDIR}
TofRecEventDir=${TOFRECEVENTROOT}/${BINDIR}
GdmlToRootDir=${GDMLTOROOTROOT}/${BINDIR}
GdmlManagementDir=${GDMLMANAGEMENTROOT}/${BINDIR}
ROOTGeoDir=${ROOTGEOROOT}/${BINDIR}
EmcRecGeoSvcDir=${EMCRECGEOSVCROOT}/${BINDIR}
EmcRecEventModelDir=${EMCRECEVENTMODELROOT}/${BINDIR}
ExtEventDir=${EXTEVENTROOT}/${BINDIR}
LessTifDir=${LESSTIFROOT}/${BINDIR}
BesGeant4Dir=${BESGEANT4ROOT}/${BINDIR}
GdmlToG4Dir=${GDMLTOG4ROOT}/${BINDIR}
G4GeoDir=${G4GEOROOT}/${BINDIR}
MucGeomSvcDir=${MUCGEOMSVCROOT}/${BINDIR}
MucRecEventDir=${MUCRECEVENTROOT}/${BINDIR}
EvtRecEventDir=${EVTRECEVENTROOT}/${BINDIR}
ReadDBBaseDir=${READDBBASEROOT}/${BINDIR}
BesTimerSvcDir=${BESTIMERSVCROOT}/${BINDIR}
MagneticFieldDir=${MAGNETICFIELDROOT}/${BINDIR}
VertexFitDir=${VERTEXFITROOT}/${BINDIR}
ParticleIDDir=${PARTICLEIDROOT}/${BINDIR}
JPsiDir=${JPSIROOT}/${BINDIR}
old_dir=`echo $(JPsi_project)/$(JPsi_project_release) | sed -e 's#//#/#g'`
old_base=`echo $(JPsi_cmtpath) | sed -e 's#/$(old_dir)##'`
sedcmd='s#$(old_base)##' -e 's#^/##' -e 's#/$##' -e 's#[^/]*#..#g'
new_base=`/bin/pwd | sed -e ${sedcmd}`
new_fincludes=`( echo $(includes) | sed -e 's#$(old_base)#$(new_base)#g')`
fincludes=`cmt show macro_value new_fincludes`
tag=i386_linux26
package=JPsi
version=JPsi-00-00-01
PACKAGE_ROOT=$(JPSIROOT)
srcdir=../src
bin=../$(JPsi_tag)/
javabin=../classes/
mgrdir=cmt
project=cmthome
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(boss_installarea_prefix)/$(CMTCONFIG)/lib $(boss_installarea_prefix)/share/lib $(boss_installarea_prefix)/share/bin $(cmthome_installarea_prefix)/$(CMTCONFIG)/lib $(cmthome_installarea_prefix)/share/lib $(cmthome_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(JPsi_linkopts)  $(VertexFit_linkopts)  $(ParticleID_linkopts)  $(EvtRecEvent_linkopts)  $(MdcRecEvent_linkopts)  $(TofRecEvent_linkopts)  $(EmcRecEventModel_linkopts)  $(MucRecEvent_linkopts)  $(ExtEvent_linkopts)  $(DstEvent_linkopts)  $(EvTimeEvent_linkopts)  $(MagneticField_linkopts)  $(EventModel_linkopts)  $(MdcGeomSvc_linkopts)  $(calibUtil_linkopts)  $(ReadDBBase_linkopts)  $(rdbModel_linkopts)  $(xmlBase_linkopts)  $(CalibData_linkopts)  $(facilities_linkopts)  $(RelTable_linkopts)  $(EmcRecGeoSvc_linkopts)  $(MucGeomSvc_linkopts)  $(G4Geo_linkopts)  $(Identifier_linkopts)  $(ROOTGeo_linkopts)  $(BesTimerSvc_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GdmlToG4_linkopts)  $(BesGeant4_linkopts)  $(BesCLHEP_linkopts)  $(MYSQL_linkopts)  $(GdmlToRoot_linkopts)  $(GdmlManagement_linkopts)  $(LessTif_linkopts)  $(BesExternalArea_linkopts)  $(ExternalPolicy_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(BesFortranPolicy_linkopts)  $(Reflex_linkopts)  $(BesROOT_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(HepMC_linkopts)  $(CLHEP_linkopts)  $(HepPDT_linkopts)  $(XercesC_linkopts)  $(CERNLIB_linkopts)  $(CASTOR_linkopts)  $(cernlib_linkopts)  $(LCG_Settings_linkopts)  $(ExternalComponents_linkopts)  $(LCG_Configuration_linkopts)  $(Xt_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
boss_installarea_prefix=$(cmt_installarea_prefix)
boss_installarea_prefix_remove=$(boss_installarea_prefix)
cmthome_installarea_prefix=$(cmt_installarea_prefix)
cmthome_installarea_prefix_remove=$(cmthome_installarea_prefix)
cmt_installarea_linkopts= -L/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/$(cmthome_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/$(boss_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
cmthome_install_include= /afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/$(cmthome_installarea_prefix)/include 
boss_install_include= /afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/$(boss_installarea_prefix)/include 
GAUDI_install_include= /afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/$(GAUDI_installarea_prefix)/include 
GAUDI_install_python=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/$(GAUDI_installarea_prefix)/python
boss_install_python=/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/$(boss_installarea_prefix)/python
cmthome_install_python=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/$(cmthome_installarea_prefix)/python
JOBOPTSEARCHPATH=,/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/jobOptions,/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/jobOptions,/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/jobOptions,/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/InstallArea/jobOptions
DATAPATH=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/PartPropSvc/share
XMLPATH=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/InstallArea/XML:/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/XML:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep1.9.3.1/GAUDI_v19r4/InstallArea/XML:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a/InstallArea/XML
constituents= install_includes  JPsi install_runtime config install_includes 
CMTINSTALLAREA=/afs/ihep.ac.cn/users/n/nikolaev/cmthome/workarea/$(cmt_installarea_prefix)
use_requirements=requirements $(CMTROOT)/mgr/requirements $(VERTEXFITROOT)/cmt/requirements $(PARTICLEIDROOT)/cmt/requirements $(EVTRECEVENTROOT)/cmt/requirements $(MDCRECEVENTROOT)/cmt/requirements $(TOFRECEVENTROOT)/cmt/requirements $(EMCRECEVENTMODELROOT)/cmt/requirements $(MUCRECEVENTROOT)/cmt/requirements $(EXTEVENTROOT)/cmt/requirements $(DSTEVENTROOT)/cmt/requirements $(EVTIMEEVENTROOT)/cmt/requirements $(MAGNETICFIELDROOT)/cmt/requirements $(EVENTMODELROOT)/cmt/requirements $(MDCGEOMSVCROOT)/cmt/requirements $(CALIBUTILROOT)/cmt/requirements $(READDBBASEROOT)/cmt/requirements $(RDBMODELROOT)/cmt/requirements $(XMLBASEROOT)/cmt/requirements $(CALIBDATAROOT)/cmt/requirements $(FACILITIESROOT)/cmt/requirements $(RELTABLEROOT)/cmt/requirements $(EMCRECGEOSVCROOT)/cmt/requirements $(MUCGEOMSVCROOT)/cmt/requirements $(G4GEOROOT)/cmt/requirements $(IDENTIFIERROOT)/cmt/requirements $(ROOTGEOROOT)/cmt/requirements $(BESTIMERSVCROOT)/cmt/requirements $(BESPOLICYROOT)/cmt/requirements $(BESCXXPOLICYROOT)/cmt/requirements $(GAUDIINTERFACEROOT)/cmt/requirements $(GDMLTOG4ROOT)/cmt/requirements $(BESGEANT4ROOT)/cmt/requirements $(BESCLHEPROOT)/cmt/requirements $(MYSQLROOT)/cmt/requirements $(GDMLTOROOTROOT)/cmt/requirements $(GDMLMANAGEMENTROOT)/cmt/requirements $(LESSTIFROOT)/cmt/requirements $(BESEXTERNALAREAROOT)/cmt/requirements $(EXTERNALPOLICYROOT)/cmt/requirements $(GAUDIKERNELROOT)/cmt/requirements $(GAUDIPOLICYROOT)/cmt/requirements $(BESFORTRANPOLICYROOT)/cmt/requirements $(REFLEXROOT)/cmt/requirements $(BESROOTROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(GCCXMLROOT)/cmt/requirements $(BOOSTROOT)/cmt/requirements $(PYTHONROOT)/cmt/requirements $(HEPMCROOT)/cmt/requirements $(CLHEPROOT)/cmt/requirements $(HEPPDTROOT)/cmt/requirements $(XERCESCROOT)/cmt/requirements $(CERNLIBROOT)/cmt/requirements $(CASTORROOT)/cmt/requirements $(CERNLIBROOT)/cmt/requirements $(LCG_SETTINGSROOT)/cmt/requirements $(EXTERNALCOMPONENTSROOT)/cmt/requirements $(LCG_CONFIGURATIONROOT)/cmt/requirements $(XTROOT)/cmt/requirements 
use_includes= $(ppcmd)"include_dirs" $(ppcmd)"apply_pattern" $(ppcmd)"component_library" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Analysis/VertexFit/VertexFit-00-02-29/VertexDbSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Analysis/VertexFit/VertexFit-00-02-29/src/test" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/VertexFit" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/ParticleID" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/EvtRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Mdc/MdcRecEvent/MdcRecEvent-00-05-11" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/MdcRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Tof/TofRecEvent/TofRecEvent-00-02-14" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/TofRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Emc/EmcRecEventModel/EmcRecEventModel-01-01-17" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/EmcRecEventModel" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/MucRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/ExtEvent/ExtEvent-00-00-12" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/ExtEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/DstEvent/DstEvent-00-02-42" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/DstEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EvTimeEvent/EvTimeEvent-00-00-08" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/EvTimeEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/MagneticField" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/EventModel/EventModel-01-05-29" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/EventModel" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Mdc/MdcGeomSvc/MdcGeomSvc-00-01-28" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/MdcGeomSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/calibUtil" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/ReadDBBase" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/rdbModel" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/xmlBase" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/CalibData" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/facilities" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Event/RelTable/RelTable-00-00-02" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/RelTable" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/Emc/EmcRecGeoSvc/EmcRecGeoSvc-01-01-06" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/EmcRecGeoSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/MucGeomSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/G4Geo" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/DetectorDescription/Identifier/Identifier-00-02-10" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/Identifier" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/ROOTGeo" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/InstallArea/include/BesTimerSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/dist/boss/6.5.1.b/BesCxxPolicy/BesCxxPolicy-00-00-08" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Saxana/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Processes/" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Processes/Processes" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Schema/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Writer/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Evaluator/G4Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Processor/G4Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Subscribers/G4Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/G4Binding/G4Writer/G4Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/geant4/4.9.0/slc4_ia32_gcc346/geant4.9.0.p01/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/Alist/Alist-00-00-02" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/String/String-00-00-02" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/MySQL/5.0.45/slc4_ia32_gcc34/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Saxana/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Processes" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Processes/Processes" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Schema/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/Common/Writer/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/ROOTBinding/Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/ROOTBinding/Processor/Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/ROOTBinding/Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/ROOTBinding/Subscribers/Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/ROOTBinding/Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346/CPPGDML/ROOTBinding/Evaluator/Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/LessTif/Motif1.2/include" $(ppcmd)"$(BesFortranPolicy_root)/src" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/include" $(ppcmd)"$(BesROOT_root)/src" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Boost/1.33.1/slc4_ia32_gcc34/include/boost-1_33_1" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Python/2.4.2/slc4_ia32_gcc34/include/python2.4" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepMC/1.26.02/slc4_ia32_gcc34/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/1.9.3.1/slc4_ia32_gcc346/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepPDT/2.02.02/slc4_ia32_gcc34/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/XercesC/2.7.0/slc4_ia32_gcc34/include" $(ppcmd)"$(CERNLIB_root)/src" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34/include" $(ppcmd)"$(Xt_root)/src" $(ppcmd)"/usr/X11R6/include" 
use_fincludes= $(use_includes)
use_stamps= $(JPsi_stamps)  $(VertexFit_stamps)  $(ParticleID_stamps)  $(EvtRecEvent_stamps)  $(MdcRecEvent_stamps)  $(TofRecEvent_stamps)  $(EmcRecEventModel_stamps)  $(MucRecEvent_stamps)  $(ExtEvent_stamps)  $(DstEvent_stamps)  $(EvTimeEvent_stamps)  $(MagneticField_stamps)  $(EventModel_stamps)  $(MdcGeomSvc_stamps)  $(calibUtil_stamps)  $(ReadDBBase_stamps)  $(rdbModel_stamps)  $(xmlBase_stamps)  $(CalibData_stamps)  $(facilities_stamps)  $(RelTable_stamps)  $(EmcRecGeoSvc_stamps)  $(MucGeomSvc_stamps)  $(G4Geo_stamps)  $(Identifier_stamps)  $(ROOTGeo_stamps)  $(BesTimerSvc_stamps)  $(BesPolicy_stamps)  $(BesCxxPolicy_stamps)  $(GaudiInterface_stamps)  $(GdmlToG4_stamps)  $(BesGeant4_stamps)  $(BesCLHEP_stamps)  $(MYSQL_stamps)  $(GdmlToRoot_stamps)  $(GdmlManagement_stamps)  $(LessTif_stamps)  $(BesExternalArea_stamps)  $(ExternalPolicy_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(BesFortranPolicy_stamps)  $(Reflex_stamps)  $(BesROOT_stamps)  $(ROOT_stamps)  $(GCCXML_stamps)  $(Boost_stamps)  $(Python_stamps)  $(HepMC_stamps)  $(CLHEP_stamps)  $(HepPDT_stamps)  $(XercesC_stamps)  $(CERNLIB_stamps)  $(CASTOR_stamps)  $(cernlib_stamps)  $(LCG_Settings_stamps)  $(ExternalComponents_stamps)  $(LCG_Configuration_stamps)  $(Xt_stamps) 
use_cflags=  $(JPsi_cflags)  $(VertexFit_cflags)  $(ParticleID_cflags)  $(EvtRecEvent_cflags)  $(MdcRecEvent_cflags)  $(TofRecEvent_cflags)  $(EmcRecEventModel_cflags)  $(MucRecEvent_cflags)  $(ExtEvent_cflags)  $(DstEvent_cflags)  $(EvTimeEvent_cflags)  $(MagneticField_cflags)  $(EventModel_cflags)  $(MdcGeomSvc_cflags)  $(calibUtil_cflags)  $(ReadDBBase_cflags)  $(rdbModel_cflags)  $(xmlBase_cflags)  $(CalibData_cflags)  $(facilities_cflags)  $(RelTable_cflags)  $(EmcRecGeoSvc_cflags)  $(MucGeomSvc_cflags)  $(G4Geo_cflags)  $(Identifier_cflags)  $(ROOTGeo_cflags)  $(BesTimerSvc_cflags)  $(BesPolicy_cflags)  $(BesCxxPolicy_cflags)  $(GaudiInterface_cflags)  $(GdmlToG4_cflags)  $(BesGeant4_cflags)  $(BesCLHEP_cflags)  $(MYSQL_cflags)  $(GdmlToRoot_cflags)  $(GdmlManagement_cflags)  $(LessTif_cflags)  $(BesExternalArea_cflags)  $(ExternalPolicy_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(BesFortranPolicy_cflags)  $(Reflex_cflags)  $(BesROOT_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(Python_cflags)  $(HepMC_cflags)  $(CLHEP_cflags)  $(HepPDT_cflags)  $(XercesC_cflags)  $(CERNLIB_cflags)  $(CASTOR_cflags)  $(cernlib_cflags)  $(LCG_Settings_cflags)  $(ExternalComponents_cflags)  $(LCG_Configuration_cflags)  $(Xt_cflags) 
use_pp_cflags=  $(JPsi_pp_cflags)  $(VertexFit_pp_cflags)  $(ParticleID_pp_cflags)  $(EvtRecEvent_pp_cflags)  $(MdcRecEvent_pp_cflags)  $(TofRecEvent_pp_cflags)  $(EmcRecEventModel_pp_cflags)  $(MucRecEvent_pp_cflags)  $(ExtEvent_pp_cflags)  $(DstEvent_pp_cflags)  $(EvTimeEvent_pp_cflags)  $(MagneticField_pp_cflags)  $(EventModel_pp_cflags)  $(MdcGeomSvc_pp_cflags)  $(calibUtil_pp_cflags)  $(ReadDBBase_pp_cflags)  $(rdbModel_pp_cflags)  $(xmlBase_pp_cflags)  $(CalibData_pp_cflags)  $(facilities_pp_cflags)  $(RelTable_pp_cflags)  $(EmcRecGeoSvc_pp_cflags)  $(MucGeomSvc_pp_cflags)  $(G4Geo_pp_cflags)  $(Identifier_pp_cflags)  $(ROOTGeo_pp_cflags)  $(BesTimerSvc_pp_cflags)  $(BesPolicy_pp_cflags)  $(BesCxxPolicy_pp_cflags)  $(GaudiInterface_pp_cflags)  $(GdmlToG4_pp_cflags)  $(BesGeant4_pp_cflags)  $(BesCLHEP_pp_cflags)  $(MYSQL_pp_cflags)  $(GdmlToRoot_pp_cflags)  $(GdmlManagement_pp_cflags)  $(LessTif_pp_cflags)  $(BesExternalArea_pp_cflags)  $(ExternalPolicy_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(BesFortranPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(BesROOT_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(HepMC_pp_cflags)  $(CLHEP_pp_cflags)  $(HepPDT_pp_cflags)  $(XercesC_pp_cflags)  $(CERNLIB_pp_cflags)  $(CASTOR_pp_cflags)  $(cernlib_pp_cflags)  $(LCG_Settings_pp_cflags)  $(ExternalComponents_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(Xt_pp_cflags) 
use_cppflags=  $(JPsi_cppflags)  $(VertexFit_cppflags)  $(ParticleID_cppflags)  $(EvtRecEvent_cppflags)  $(MdcRecEvent_cppflags)  $(TofRecEvent_cppflags)  $(EmcRecEventModel_cppflags)  $(MucRecEvent_cppflags)  $(ExtEvent_cppflags)  $(DstEvent_cppflags)  $(EvTimeEvent_cppflags)  $(MagneticField_cppflags)  $(EventModel_cppflags)  $(MdcGeomSvc_cppflags)  $(calibUtil_cppflags)  $(ReadDBBase_cppflags)  $(rdbModel_cppflags)  $(xmlBase_cppflags)  $(CalibData_cppflags)  $(facilities_cppflags)  $(RelTable_cppflags)  $(EmcRecGeoSvc_cppflags)  $(MucGeomSvc_cppflags)  $(G4Geo_cppflags)  $(Identifier_cppflags)  $(ROOTGeo_cppflags)  $(BesTimerSvc_cppflags)  $(BesPolicy_cppflags)  $(BesCxxPolicy_cppflags)  $(GaudiInterface_cppflags)  $(GdmlToG4_cppflags)  $(BesGeant4_cppflags)  $(BesCLHEP_cppflags)  $(MYSQL_cppflags)  $(GdmlToRoot_cppflags)  $(GdmlManagement_cppflags)  $(LessTif_cppflags)  $(BesExternalArea_cppflags)  $(ExternalPolicy_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(BesFortranPolicy_cppflags)  $(Reflex_cppflags)  $(BesROOT_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(HepMC_cppflags)  $(CLHEP_cppflags)  $(HepPDT_cppflags)  $(XercesC_cppflags)  $(CERNLIB_cppflags)  $(CASTOR_cppflags)  $(cernlib_cppflags)  $(LCG_Settings_cppflags)  $(ExternalComponents_cppflags)  $(LCG_Configuration_cppflags)  $(Xt_cppflags) 
use_pp_cppflags=  $(JPsi_pp_cppflags)  $(VertexFit_pp_cppflags)  $(ParticleID_pp_cppflags)  $(EvtRecEvent_pp_cppflags)  $(MdcRecEvent_pp_cppflags)  $(TofRecEvent_pp_cppflags)  $(EmcRecEventModel_pp_cppflags)  $(MucRecEvent_pp_cppflags)  $(ExtEvent_pp_cppflags)  $(DstEvent_pp_cppflags)  $(EvTimeEvent_pp_cppflags)  $(MagneticField_pp_cppflags)  $(EventModel_pp_cppflags)  $(MdcGeomSvc_pp_cppflags)  $(calibUtil_pp_cppflags)  $(ReadDBBase_pp_cppflags)  $(rdbModel_pp_cppflags)  $(xmlBase_pp_cppflags)  $(CalibData_pp_cppflags)  $(facilities_pp_cppflags)  $(RelTable_pp_cppflags)  $(EmcRecGeoSvc_pp_cppflags)  $(MucGeomSvc_pp_cppflags)  $(G4Geo_pp_cppflags)  $(Identifier_pp_cppflags)  $(ROOTGeo_pp_cppflags)  $(BesTimerSvc_pp_cppflags)  $(BesPolicy_pp_cppflags)  $(BesCxxPolicy_pp_cppflags)  $(GaudiInterface_pp_cppflags)  $(GdmlToG4_pp_cppflags)  $(BesGeant4_pp_cppflags)  $(BesCLHEP_pp_cppflags)  $(MYSQL_pp_cppflags)  $(GdmlToRoot_pp_cppflags)  $(GdmlManagement_pp_cppflags)  $(LessTif_pp_cppflags)  $(BesExternalArea_pp_cppflags)  $(ExternalPolicy_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(BesFortranPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(BesROOT_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(HepMC_pp_cppflags)  $(CLHEP_pp_cppflags)  $(HepPDT_pp_cppflags)  $(XercesC_pp_cppflags)  $(CERNLIB_pp_cppflags)  $(CASTOR_pp_cppflags)  $(cernlib_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(ExternalComponents_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(Xt_pp_cppflags) 
use_fflags=  $(JPsi_fflags)  $(VertexFit_fflags)  $(ParticleID_fflags)  $(EvtRecEvent_fflags)  $(MdcRecEvent_fflags)  $(TofRecEvent_fflags)  $(EmcRecEventModel_fflags)  $(MucRecEvent_fflags)  $(ExtEvent_fflags)  $(DstEvent_fflags)  $(EvTimeEvent_fflags)  $(MagneticField_fflags)  $(EventModel_fflags)  $(MdcGeomSvc_fflags)  $(calibUtil_fflags)  $(ReadDBBase_fflags)  $(rdbModel_fflags)  $(xmlBase_fflags)  $(CalibData_fflags)  $(facilities_fflags)  $(RelTable_fflags)  $(EmcRecGeoSvc_fflags)  $(MucGeomSvc_fflags)  $(G4Geo_fflags)  $(Identifier_fflags)  $(ROOTGeo_fflags)  $(BesTimerSvc_fflags)  $(BesPolicy_fflags)  $(BesCxxPolicy_fflags)  $(GaudiInterface_fflags)  $(GdmlToG4_fflags)  $(BesGeant4_fflags)  $(BesCLHEP_fflags)  $(MYSQL_fflags)  $(GdmlToRoot_fflags)  $(GdmlManagement_fflags)  $(LessTif_fflags)  $(BesExternalArea_fflags)  $(ExternalPolicy_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(BesFortranPolicy_fflags)  $(Reflex_fflags)  $(BesROOT_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(Python_fflags)  $(HepMC_fflags)  $(CLHEP_fflags)  $(HepPDT_fflags)  $(XercesC_fflags)  $(CERNLIB_fflags)  $(CASTOR_fflags)  $(cernlib_fflags)  $(LCG_Settings_fflags)  $(ExternalComponents_fflags)  $(LCG_Configuration_fflags)  $(Xt_fflags) 
use_pp_fflags=  $(JPsi_pp_fflags)  $(VertexFit_pp_fflags)  $(ParticleID_pp_fflags)  $(EvtRecEvent_pp_fflags)  $(MdcRecEvent_pp_fflags)  $(TofRecEvent_pp_fflags)  $(EmcRecEventModel_pp_fflags)  $(MucRecEvent_pp_fflags)  $(ExtEvent_pp_fflags)  $(DstEvent_pp_fflags)  $(EvTimeEvent_pp_fflags)  $(MagneticField_pp_fflags)  $(EventModel_pp_fflags)  $(MdcGeomSvc_pp_fflags)  $(calibUtil_pp_fflags)  $(ReadDBBase_pp_fflags)  $(rdbModel_pp_fflags)  $(xmlBase_pp_fflags)  $(CalibData_pp_fflags)  $(facilities_pp_fflags)  $(RelTable_pp_fflags)  $(EmcRecGeoSvc_pp_fflags)  $(MucGeomSvc_pp_fflags)  $(G4Geo_pp_fflags)  $(Identifier_pp_fflags)  $(ROOTGeo_pp_fflags)  $(BesTimerSvc_pp_fflags)  $(BesPolicy_pp_fflags)  $(BesCxxPolicy_pp_fflags)  $(GaudiInterface_pp_fflags)  $(GdmlToG4_pp_fflags)  $(BesGeant4_pp_fflags)  $(BesCLHEP_pp_fflags)  $(MYSQL_pp_fflags)  $(GdmlToRoot_pp_fflags)  $(GdmlManagement_pp_fflags)  $(LessTif_pp_fflags)  $(BesExternalArea_pp_fflags)  $(ExternalPolicy_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(BesFortranPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(BesROOT_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(HepMC_pp_fflags)  $(CLHEP_pp_fflags)  $(HepPDT_pp_fflags)  $(XercesC_pp_fflags)  $(CERNLIB_pp_fflags)  $(CASTOR_pp_fflags)  $(cernlib_pp_fflags)  $(LCG_Settings_pp_fflags)  $(ExternalComponents_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(Xt_pp_fflags) 
use_libraries= $(VertexFit_libraries)  $(ParticleID_libraries)  $(EvtRecEvent_libraries)  $(MdcRecEvent_libraries)  $(TofRecEvent_libraries)  $(EmcRecEventModel_libraries)  $(MucRecEvent_libraries)  $(ExtEvent_libraries)  $(DstEvent_libraries)  $(EvTimeEvent_libraries)  $(MagneticField_libraries)  $(EventModel_libraries)  $(MdcGeomSvc_libraries)  $(calibUtil_libraries)  $(ReadDBBase_libraries)  $(rdbModel_libraries)  $(xmlBase_libraries)  $(CalibData_libraries)  $(facilities_libraries)  $(RelTable_libraries)  $(EmcRecGeoSvc_libraries)  $(MucGeomSvc_libraries)  $(G4Geo_libraries)  $(Identifier_libraries)  $(ROOTGeo_libraries)  $(BesTimerSvc_libraries)  $(BesPolicy_libraries)  $(BesCxxPolicy_libraries)  $(GaudiInterface_libraries)  $(GdmlToG4_libraries)  $(BesGeant4_libraries)  $(BesCLHEP_libraries)  $(MYSQL_libraries)  $(GdmlToRoot_libraries)  $(GdmlManagement_libraries)  $(LessTif_libraries)  $(BesExternalArea_libraries)  $(ExternalPolicy_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(BesFortranPolicy_libraries)  $(Reflex_libraries)  $(BesROOT_libraries)  $(ROOT_libraries)  $(GCCXML_libraries)  $(Boost_libraries)  $(Python_libraries)  $(HepMC_libraries)  $(CLHEP_libraries)  $(HepPDT_libraries)  $(XercesC_libraries)  $(CERNLIB_libraries)  $(CASTOR_libraries)  $(cernlib_libraries)  $(LCG_Settings_libraries)  $(ExternalComponents_libraries)  $(LCG_Configuration_libraries)  $(Xt_libraries) 
JPsi_use_linkopts=  $(JPsi_linkopts)  $(VertexFit_linkopts)  $(ParticleID_linkopts)  $(EvtRecEvent_linkopts)  $(MdcRecEvent_linkopts)  $(TofRecEvent_linkopts)  $(EmcRecEventModel_linkopts)  $(MucRecEvent_linkopts)  $(ExtEvent_linkopts)  $(DstEvent_linkopts)  $(EvTimeEvent_linkopts)  $(MagneticField_linkopts)  $(EventModel_linkopts)  $(MdcGeomSvc_linkopts)  $(calibUtil_linkopts)  $(ReadDBBase_linkopts)  $(rdbModel_linkopts)  $(xmlBase_linkopts)  $(CalibData_linkopts)  $(facilities_linkopts)  $(RelTable_linkopts)  $(EmcRecGeoSvc_linkopts)  $(MucGeomSvc_linkopts)  $(G4Geo_linkopts)  $(Identifier_linkopts)  $(ROOTGeo_linkopts)  $(BesTimerSvc_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GdmlToG4_linkopts)  $(BesGeant4_linkopts)  $(BesCLHEP_linkopts)  $(MYSQL_linkopts)  $(GdmlToRoot_linkopts)  $(GdmlManagement_linkopts)  $(LessTif_linkopts)  $(BesExternalArea_linkopts)  $(ExternalPolicy_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(BesFortranPolicy_linkopts)  $(Reflex_linkopts)  $(BesROOT_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(HepMC_linkopts)  $(CLHEP_linkopts)  $(HepPDT_linkopts)  $(XercesC_linkopts)  $(CERNLIB_linkopts)  $(CASTOR_linkopts)  $(cernlib_linkopts)  $(LCG_Settings_linkopts)  $(ExternalComponents_linkopts)  $(LCG_Configuration_linkopts)  $(Xt_linkopts) 
all_constituents= $(constituents)
constituentsclean= install_includesclean configclean install_runtimeclean JPsiclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make JPsi_check_install_runtime 
cmt_actions_constituentsclean= JPsi_check_install_runtimeclean makeclean 
